# The URL the site will be built for
base_url = "https://zola-my-id-vn.jakeclark38b.workers.dev"

title = "Blog cá»§a JakeClark"
default_language = "vi"
theme = "tabi"

compile_sass = true
build_search_index = false
generate_feeds = true

taxonomies = [{ name = "tags", feed = true }]

[languages.en]
title = "JakeClark's Blog"
taxonomies = [{ name = "tags", feed = true }]
build_search_index = false
generate_feeds = true

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
skin = "mint"
theme_switcher = true
default_theme = ""
browser_theme_color = "#087e96"
compact_tags = true
socials = []
menu = [
    { name = "linux", url = "linux" },
]
