# The URL the site will be built for
base_url = "https://blog.thanhnc.id.vn"

title = "Blog cá»§a JakeClark"
default_language = "vi"
theme = "tabi"

compile_sass = true
build_search_index = false
generate_feeds = true

taxonomies = [{ name = "tags", feed = true }]

[languages.en]
title = "JakeClark's Blog"
taxonomies = [{ name = "tags", feed = true }]
build_search_index = false
generate_feeds = true

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
skin = "mint"
theme_switcher = true
default_theme = ""
browser_theme_color = "#087e96"
compact_tags = true
menu = [
    { name = "linux", url = "linux" },
    { name = "ctf", url = "ctf" },
]
footer_menu = [
    { name = "linux", url = "linux" },
    { name = "ctf", url = "ctf" },
]
# Anonymous like button with custom icon
iine = true 
iine_icon = "thumbs_up"
show_previous_next_article_links = true
invert_previous_next_article_links = true
quick_navigation_buttons = true
favicon_emoji = "ðŸ“–"
socials = [
    { name = "email", url = "mailto:contact@thanhnc.id.vn", icon = "email" },
    { name = "github", url = "https://github.com/JakeClark-chan", icon = "github" },
    { name = "linkedin", url = "https://www.linkedin.com/in/ngchithanh", icon = "linkedin" },
    { name = "facebook", url = "https://facebook.com/nguyenchithanh21", icon = "facebook" },
    { name = "telegram", url = "https://t.me/jakeclark38a", icon = "telegram" },
]

[extra.giscus]
enabled_for_all_posts = true
automatic_loading = true
repo = "JakeClark-chan/zola-my-id-vn"
repo_id = "R_kgDORXqQpA"
category = "General"
category_id = "DIC_kwDORXqQpM4C3Rqg"
mapping = "pathname"
strict_title_matching = 1  # 1 to enable, 0 to disable.
enable_reactions = 1  # 1 to enable, 0 to disable.
comment_box_above_comments = true
light_theme = "noborder_light"
dark_theme = "noborder_dark"
lang = ""  # Leave blank to match the page's language.
lazy_loading = true